### ISSUE TITLE
text2vec errors

### ISSUE THREAD

**Issue by nickj95** [dustinstoltz/CMDist#1]
Hi there. I enjoyed your article and was looking forward to using the technique. However, I'm encountering some persistent errors with what I'm guessing is the text2vec implementation. Mainly, I can't get CMDist to run anymore -- whereas in the past, I got the replication materials up and running. 

There's a particularly annoying issue with this following error: 
` Error in .subset2(public_bind_env, "initialize")(...) : 
  is.matrix(wv) is not TRUE `

Which shouldn't be true given that my wv variable is `is.matrix(word_vectors) [1] TRUE` . I'd appreciate your thoughts on troubleshooting this issue.

**Comment by Marshall-Soc** [comment]
Hi nickj95,

Thanks for your message! We believe we have encountered this error before and are working on replicating it. 

What versions of `CMDist` and `text2vec` are you currently running?

~Marshall

**Comment by nickj95** [comment]
Thanks for your quick response! 

I'm running text2vec_0.5.1 and CMDist_0.5.0. I can try updating a few different things and seeing what if anything changes. 

If I'm not wrong the error calls back to some sort of initialization function in RWMD.

-- Nick

**Comment by nickj95** [comment]
Ok. 

I was right about text2vec -- it seems that 0.5.1 has some sort of weird reaction in R 3.6. Upgrading to the newer text2vec solved it. 

Cheers!
Nick

**Comment by dustinstoltz** [comment]
Glad it's working now and thanks for letting us know about that, Nick!
