### ISSUE TITLE
Manually load the dependency stringr

### ISSUE THREAD

**Issue by non87** [dustinstoltz/CMDist#6]
Thanks for the great package. I notice a little problem while running it for the first time.

I installed the package through `devtools` and loaded it in a clean environment. However, the function `cmdist` could not finish to run since `.prepINPUT` would get stuck at line 24, where it calls `str_trim()` from `stringr`, which is not loaded. Once I load `stringr`, everything runs smoothly. Likely, this is not what should happen.

**Comment by dustinstoltz** [comment]
Thanks for pointing that out! Fixed.
